name: Melos
repository: https://github.com/invertase/melos
packages:
  - packages/**
  - "*"

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

ide:
  intellij: true

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
    select-package:
      ignore:
        - "*monorepo*"

  test:
    description: Run tests in a specific package.
    # TODO(Salakar) 'dart pub get' is necessary for the 'melos' package as we're using it on itself
    run: melos exec --concurrency=1 -- "dart pub get && dart pub run test --reporter expanded"
    select-package:
      dir-exists:
        - "test/"
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true

  format: dart format -o write .

  format-check:
    run: melos exec flutter format . --set-exit-if-changed
    description: Run `flutter format` checks for all packages.

  version: dart run scripts/generate_version.dart
