name: Melos
repository: https://github.com/invertase/melos
packages:
  - packages/*
ignore:
  - packages/melos_flutter_deps_check
categories:
  all:
    - packages/*

command:
  bootstrap:
    environment:
      sdk: ^3.6.0
    dependencies:
      ansi_styles: ^0.3.2+1
      args: ^2.6.0
      cli_launcher: ^0.3.1
      cli_util: ^0.4.2
      collection: any
      conventional_commit: ^0.6.0+1
      file: ^7.0.1
      glob: ^2.1.2
      graphs: ^2.3.2
      http: ^1.2.2
      meta: any
      mustache_template: ^2.0.0
      path: any
      platform: ^3.1.6
      pool: ^1.5.1
      prompts: ^2.0.0
      pub_semver: ^2.1.5
      pub_updater: ^0.5.0
      pubspec_parse:
        git:
          url: https://github.com/dart-lang/tools.git
          path: pkgs/pubspec_parse
      string_scanner: ^1.3.0
      yaml: ^3.1.3
      yaml_edit: ^2.2.2
    dev_dependencies:
      mockito: ^5.4.5
      test: any
      path: ^1.9.1
      yaml: ^3.1.3
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
    hooks:
      preCommit: |
        dart run scripts/generate_version.dart && \
        git add packages/melos/lib/version.g.dart

ide:
  intellij: true

scripts:
  test:
    description: Run tests in a specific package.
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true

  activate:
    description: Activate the local version of melos for development.
    run:
      dart pub global activate --source="path" . --executable="melos"
      --overwrite

  activate:pub:
    description: Activate the published version of melos.
    run: dart pub global activate melos --overwrite

  upgrade: melos exec flutter pub upgrade
