name: Melos
packages:
  - packages/**
  - "*"

ide:
  intellij:
    true
    # TODO(Salakar): more granular control
    # use_workspace_tasks: true
    # use_flutter_test_tasks: true
    # use_flutter_run_tasks: true
    # use_dart_test_tasks: false
  vscode:
    false
    # TODO(Salakar): more granular control
    # use_workspace_tasks: true
    # use_flutter_test_tasks: true
    # use_flutter_run_tasks: true
    # use_dart_test_tasks: false
    # use_recommended_settings: true

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze . --fatal-infos"
    description: Run dart analyzer in a specific package.
    select-package:
      ignore:
        - "*monorepo*"

  test:
    description: Run tests in a specific package.
    run: melos exec -c 1 -- "dart pub run test test/\$MELOS_PACKAGE_NAME_test.dart"
    select-package:
      file-exists:
        - "test/$MELOS_PACKAGE_NAME_test.dart"

  format: dart format -o write .
  version: dart run scripts/generate_version.dart

environment:
  sdk: ">=2.2.2 <3.0.0"
