name: Melos
repository: https://github.com/invertase/melos
packages:
  - .
  - packages/*
ignore:
  - packages/melos_flutter_deps_check

command:
  bootstrap:
    environment:
      sdk: ">=3.0.0 <4.0.0"
    dependencies:
      ansi_styles: ^0.3.2+1
      args: ^2.4.2
      cli_launcher: ^0.3.1
      cli_util: ^0.4.1
      collection: ^1.18.0
      conventional_commit: ^0.6.0+1
      file: ^7.0.0
      glob: ^2.1.2
      graphs: ^2.3.1
      http: ^1.1.0
      meta: ^1.10.0
      mustache_template: ^2.0.0
      path: ^1.8.3
      platform: ^3.1.4
      pool: ^1.5.1
      prompts: ^2.0.0
      pub_semver: ^2.1.4
      pub_updater: ^0.4.0
      pubspec: ^2.3.0
      string_scanner: ^1.2.0
      yaml: ^3.1.2
      yaml_edit: ^2.1.1
    dev_dependencies:
      collection: ^1.18.0
      mockito: ^5.4.2
      test: ^1.24.9
      path: ^1.9.0
      yaml: ^3.1.2
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # Only allow versioning to happen on main branch.
    branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true
    hooks:
      preCommit: |
        dart run scripts/generate_version.dart && \
        git add packages/melos/lib/version.g.dart

ide:
  intellij: true

scripts:
  test:
    description: Run tests in a specific package.
    run: dart test
    exec:
      concurrency: 1
    packageFilters:
      dirExists:
        - test
    # This tells Melos tests to ignore env variables passed to tests from `melos run test`
    # as they could change the behaviour of how tests filter packages.
    env:
      MELOS_TEST: true

  activate:
    description: Activate the local version of melos for development.
    run:
      dart pub global activate --source="path" . --executable="melos"
      --overwrite

  activate:pub:
    description: Activate the published version of melos.
    run: dart pub global activate melos --overwrite
