name: Bug Report
description: Create a report to help us improve.
title: "fix:  "
labels: ["bug", "triage"]
# assignees:
#   - ...
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues.
          required: true

  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Version
      description: |
        What version of Melos are you running?

        > Tip: You can use `melos --version` to get the current version.
      placeholder: "1.2.0"

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Description
      description: |
        Give us a clear and concise description of what the bug is and what happened.
      placeholder: Melos throws an error if I run this command...

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Steps to reproduce
      description: |
        What steps can we take to reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: Expected behavior
      description: |
        What did you expect to happen?
      placeholder: |
        When running ..., Melos should ...

  - type: textarea
    id: screenshots
    validations:
      required: false
    attributes:
      label: Screenshots
      description: |
        If you have any screenshots, please attach them here.

  - type: textarea
    id: comments
    attributes:
      label: Additional context and comments
      description: |
        Anything else you want to say?
