# Updates the `melos-latest` branch to the latest Melos release.
name: Latest Melos release

on:
  workflow_dispatch:
  push:
    tags:
      - melos-v*

jobs:
  release_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git push -f origin HEAD:melos-latest
