name: all_packages

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"

  dart_version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"

  melos_flutter_deps_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"

  format:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"

  test_linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"

  test_macos:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"

  test_windows:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skipped"
